version: '3'
services:
  web:
    image: node:8.11.2
    ports:
      - "3000:3000"
    volumes: 
      - ./webapp:/code
    working_dir: /code
    command: yarn start
  backend:
    build: ./backend
    volumes: 
      - ./backend/api:/code
    working_dir: /code
    command:  bash -c "rm -f /code/tmp/pids/server.pid && bin/rails server"
    ports:
      - "3001:3000"
